version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd $CODEBUILD_SRC_DIR/devpro
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - cd $CODEBUILD_SRC_DIR/devpro
      - npm run build

artifacts:
  files:
    - 'appspec.yml'
    - 'scripts/**/*'
    - '**/*'
  base-directory: devpro/build
